---
title: "results_analysis"
author: "Louis Magowan"
date: '2022-08-08'
output: html_document
---

# Imports and Setup

```{r}
# Load packages
packages <- c("tidyverse", "ggplot2", 
              "ggthemes", "stringi",
              "tools", "glue", "rlang")
suppressMessages(invisible(lapply(packages, library, character.only=TRUE)))

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
```

```{r}
# Read in data
data <- read.csv("data/predicted_diffs-processed.csv")
# Tidy up factor labels for plotting
old_factor_labels <- c('Attainment Quantile', 'Eal', 'Fsm', 'Sen',
                       "Centretypedesc", "Idaci Quantile")
new_factor_labels <- c('Prior Attainment', 'EAL', 'FSM', "SEN",
                       "Centre Type", "IDACI")
data$factor <- stri_replace_all_regex(data$factor,
                                      pattern = c('_', "X"),
                                      replacement = c(" ", " X\n"),
                                      vectorize=FALSE) %>%
  str_to_title() %>% 
  stri_replace_all_regex(pattern = old_factor_labels,
                         replacement = new_factor_labels,
                         vectorize=FALSE)
# Tidying up factor value labels for plotting
data$factor_value <- data$factor_value %>% toTitleCase()
# Create interaction order col for easier filtering
data$interactions <- str_count(data$factor, pattern = "X\n") + 1
```


```{r}
# Save theme
my_theme <- theme_economist() +
  theme(axis.text.x = element_text(vjust = 2),
          axis.text.y = element_text(hjust = 1.2),
          axis.title = element_text(face = "bold"),
          plot.title = element_text(vjust = 3, hjust = 0.3),
          legend.title = element_text(face = "bold"),
          legend.text = element_text(size = 10),
          legend.position = "bottom",
          legend.background = element_rect(fill = "white"))

# Get columns needed for output
table_cols <- c("factor", "factor_value", "cag_diff",
                "centreassessmentgrade", "predictions",
                "welch.p_val")

# Get factor levels to reorder
prior_attainment_levels <- c("Very Low", "Low", "Medium",
                             "High", "Very High")
idaci_levels <- c("Very High IDACI", "High IDACI",
                  "Medium IDACI", "Low IDACI",
                  "Very Low IDACI")
```


```{r}
# Create a function to help decide which interactions to report on
# It compares the min and max CAG diff in each factor/grouping variable
# calculates the range, then returns those ranges sorted
calc_range_interaction <- function(df, n_interactions){
  n_way_df <- df %>% filter(interactions == n_interactions) %>% 
    select(factor) %>%
    unique()
  n_way_df <- df %>% filter(factor %in% n_way_df$factor)
  n_way_df <- n_way_df %>% group_by(factor) %>%
    summarise(max_val = max(cag_diff),
              min_val = min(cag_diff)) %>% 
    mutate(range = max_val - min_val) %>% arrange(desc(range))
  
  return(n_way_df)
}
```

```{r}
# Create a function for getting df into output format for Word tables
tidy_table <- function(df, table_cols){
  # Write <0.001 for pvals, else round to 3dp
  df$welch.p_val <- ifelse(df$welch.p_val < 0.001, 
                                "<0.001", 
                                round(df$welch.p_val, 4))
  # Write ethnicity more neatly
  rep_str = c('WHIT'='White','BLAC'='Black',
            'ASIA'='Asian', "CHIN"="Chinese",
            "MIXD" = "Mixed")
  df$factor_value <- str_replace_all(df$factor_value, rep_str)
  # Write factor more neatly
  df$factor <- df$factor %>% str_replace_all(rep_str <- c("X\n"="X "))
  # Save number results as table in same order as graph
  df <- df[order(nrow(df):1), ] %>% select(table_cols) %>% 
    # Round the remaining columns
    mutate_if(is.numeric, round, 3)
  return(df)
}
```

# Main Effects

```{r}
# Filter to only the relevant main effects
main_factors <- c("IDACI", "FSM", "EAL",
                  "Ethnicity", "Gender", "SEN") %>% sort()
# Go through main results, sorting by cag_diff within each group
main_df <- data.frame()
for (factor_var in main_factors){
  subdf <- data %>% filter(factor == factor_var)
  subdf <- subdf[order(subdf$cag_diff, decreasing = TRUE), ]
  main_df <- rbind(main_df, subdf)
}
# Make factor values a factor, so they are ordered in plot
main_df$factor_value  <- factor(main_df$factor_value,
                                     levels = unique(main_df$factor_value))
# Plot main effects
plot <- ggplot(data = main_df, mapping = aes(x = cag_diff,
                                               y = factor_value,
                                               color = factor,
                                               shape = factor)) +
  # Add points
  geom_point(size = 3) + 
  # Add titles and labels
  ggtitle("Conditional Avg. Treatment Effects") +
  xlab("CATE (GCSE Grade Points)") + ylab("Category Value") +
  # Retitle legend
  labs(color='Category') + labs(shape='Category') +
  # Adjust theme
  my_theme + theme(axis.text.y = element_text(hjust = 1.1))

# Get plot build in order to access the colours used
plot_build <- ggplot_build(plot)
# Add the plot colours to the yticks
plot <- plot + 
  theme(axis.text.y = element_text(color = plot_build$data[[1]]$colour))
# Save plot
ggsave("main_effects/main_effects.png", plot)
plot
```


Also redo the df to include prior attainment in the table
```{r}
# Filter to only the relevant main effects
main_factors <- c("IDACI", "FSM", "EAL", "Prior Attainment",
                  "Ethnicity", "Gender", "SEN") %>% sort()
# Go through main results, sorting by cag_diff within each group
main_df <- data.frame()
for (factor_var in main_factors){
  subdf <- data %>% filter(factor == factor_var)
  subdf <- subdf[order(subdf$cag_diff, decreasing = TRUE), ]
  main_df <- rbind(main_df, subdf)
}

# Tidy up results for table format
main_df %>% tidy_table(table_cols) %>% 
  write.csv("main_effects/main_table.csv",
            row.names = FALSE)
```

# Two-Way Interactions

```{r}
# Find the 2 way interactions that have greatest differences between max and min
calc_range_interaction(data, n_interactions = 2)
```

```{r}
# Get list of two-way vars
two_way_vars <- calc_range_interaction(data, n_interactions = 2) %>% select(factor)
two_way_vars <- two_way_vars$factor

# Rework factor value into two cols for plotting
two_data <- data %>% filter(interactions == 2) %>%
  separate(factor_value, c("var1", "var2"),
           remove = FALSE,
           sep = " X ")
# Iterate through each two-way interaction
for (factor_var in two_way_vars){
  # Filter to current two-way interaction
  subdf <- two_data %>% filter(factor == factor_var)
  # Order on Var 1
  subdf <- subdf[order(subdf$var1), ]
  # Check if prior attainment is in var1  and reorder if true
  if (any(str_detect(subdf$var1, "Low") == 1) &&
      (any(str_detect(subdf$var1, "IDACI") == 0))){
    subdf$var1 <- subdf$var1 %>% factor(levels = prior_attainment_levels)
  }
  # Check if prior attainment is in var2  and reorder if true
  if (any(str_detect(subdf$var2, "Low") == 1) &&
      (any(str_detect(subdf$var2, "IDACI") == 0))){
    subdf$var2 <- subdf$var2 %>% factor(levels = prior_attainment_levels)
  }
    # Check if ICADI is in var1  and reorder if true
  if (any(str_detect(subdf$var1, "Low") == 1) &&
      (any(str_detect(subdf$var1, "IDACI") == 1))){
    subdf$var1 <- subdf$var1 %>% factor(levels = idaci_levels)
  }
  # Check if IDACI is in var2  and reorder if true
  if (any(str_detect(subdf$var2, "Low") == 1) &&
      (any(str_detect(subdf$var2, "IDACI") == 1))){
    subdf$var2 <- subdf$var2 %>% factor(levels = idaci_levels)
  }
  # Get neatened var name
  clean_name <- factor_var %>% str_replace("\n", " ")
  # Get var1 neatened name
  legend_name <- factor_var %>% str_split(" X\n") %>% unlist()
  legend_name <- legend_name[2]

  # Plot main effects
  plot <- ggplot(data = subdf, mapping = aes(x = cag_diff,
                                             y = var1,
                                             color = var2,
                                             shape = var2)) +
    # Add points
    geom_point(size = 3) + 
    # Add titles and labels
    ggtitle(glue("CATE | ", clean_name)) +
    xlab("Conditional Avg. Treatment Effect (GCSE Grade Points)") +
    ylab(clean_name) +
    # Retitle legend
    labs(color=legend_name) + labs(shape=legend_name) +
    # Adjust theme
    my_theme + theme(plot.title = element_text(hjust = 0.4)) +
    guides(colour=guide_legend(nrow=2), shape=guide_legend(nrow=2))
  # Save plot
  # Get save name
  save_name <- factor_var %>% str_to_lower() %>% str_replace_all(" x\n", "_")
  plot_save_name <- glue("two_way_effects/graphs/", save_name, ".png")
  ggsave(plot_save_name, plot)
  
  # Also save table
  subdf %>% tidy_table(table_cols) %>%
  write.csv(glue("two_way_effects/tables/", save_name, ".csv"), row.names = F)
  
  # break
}
```

# Three-Way Interactions

```{r}
# Find the 3 way interactions that have greatest differences between max and min
calc_range_interaction(data, n_interactions = 3)
```


```{r}
# Get list of three-way vars
three_way_vars <- calc_range_interaction(data, n_interactions = 3) %>% select(factor)
three_way_vars <- three_way_vars$factor

# Rework factor value into two cols for plotting
three_data <- data %>% filter(interactions == 3) %>%
  separate(factor_value, c("var1", "var2", "var3"),
           remove = FALSE,
           sep = " X ")
# Dynamically plot facet using the var with least features
col_list <- c("var1", "var2", "var3")

# Iterate through each two-way interaction
for (factor_var in three_way_vars){
  # Filter to current two-way interaction
  subdf <- three_data %>% filter(factor == factor_var)
  # Order on Var 1
  subdf <- subdf[order(subdf$var1), ]
  # Check if prior attainment is in var1  and reorder if true
  if (any(str_detect(subdf$var1, "Low") == 1) &&
      (any(str_detect(subdf$var1, "IDACI") == 0))){
    subdf$var1 <- subdf$var1 %>% factor(levels = prior_attainment_levels)
  }
  # Check if prior attainment is in var2  and reorder if true
  if (any(str_detect(subdf$var2, "Low") == 1) &&
      (any(str_detect(subdf$var2, "IDACI") == 0))){
    subdf$var2 <- subdf$var2 %>% factor(levels = prior_attainment_levels)
  }
  # Check if prior attainment is in var3  and reorder if true
  if (any(str_detect(subdf$var3, "Low") == 1) &&
      (any(str_detect(subdf$var3, "IDACI") == 0))){
    subdf$var3 <- subdf$var3 %>% factor(levels = prior_attainment_levels)
  }
    # Check if ICADI is in var1  and reorder if true
  if (any(str_detect(subdf$var1, "Low") == 1) &&
      (any(str_detect(subdf$var1, "IDACI") == 1))){
    subdf$var1 <- subdf$var1 %>% factor(levels = idaci_levels)
  }
  # Check if IDACI is in var2  and reorder if true
  if (any(str_detect(subdf$var2, "Low") == 1) &&
      (any(str_detect(subdf$var2, "IDACI") == 1))){
    subdf$var2 <- subdf$var2 %>% factor(levels = idaci_levels)
  }
  # Check if IDACI is in var3  and reorder if true
  if (any(str_detect(subdf$var3, "Low") == 1) &&
      (any(str_detect(subdf$var3, "IDACI") == 1))){
    subdf$var3 <- subdf$var3 %>% factor(levels = idaci_levels)
  }
  # Get neatened var name
  clean_name <- factor_var %>% str_replace_all("\n", " ")

  # Find the column with the least features
  facet_col <- lapply(subdf[c("var1", "var2", "var3")],
                      function(x) c((length(unique(x))))) %>% 
    which.min() %>% names()
  # Get the non-facet cols
  non_facet_cols <- col_list[!(col_list %in% facet_col)]
  # Get neatened name for legend
  legend_name <- factor_var %>% str_split(" X\n") %>% unlist()
  legend_name <- legend_name[!(col_list %in% facet_col)][2]
  # Plot main effects
  plot <- ggplot(data = subdf, mapping = aes(x = cag_diff,
                                             y = !!sym(non_facet_cols[1]),
                                             color = !!sym(non_facet_cols[2]),
                                             shape = !!sym(non_facet_cols[2]))) +
  # Add points
  geom_point(size = 3) +
  facet_wrap(sym(facet_col)) +
    # Add titles and labels
    ggtitle(glue("CATE | ", clean_name)) +
    xlab("Conditional Avg. Treatment Effect (GCSE Grade Points)") +
    ylab(clean_name) +
    # Retitle legend
    labs(color=legend_name) + labs(shape=legend_name) +
    # Adjust theme
    my_theme + theme(plot.title = element_text(hjust = 0.4)) +
    guides(colour=guide_legend(nrow=2), shape=guide_legend(nrow=2)) +
    theme(strip.background = element_rect(color = "black",
                                          fill="grey"),
          panel.border = element_rect(color = "black", fill = NA, size = 1))+
    
    theme(strip.text = element_text(colour = 'white'))

  # Save plot
  # Get save name
  save_name <- factor_var %>% str_to_lower() %>% str_replace_all(" x\n", "_")
  plot_save_name <- glue("three_way_effects/graphs/", save_name, ".png")
  ggsave(plot_save_name, plot)

  # Also save table
  subdf %>% tidy_table(table_cols) %>%
  write.csv(glue("three_way_effects/tables/", save_name, ".csv"), row.names = F)
}
```

```{r}
# Ethnicity X IDACI X Prior Attainment
# Filter data and sort by CAG diff
three_way_df <- data %>% filter(factor == "Ethnicity X\nIDACI X\nPrior Attainment") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
three_way_df <- rbind(head(three_way_df, 10), tail(three_way_df, 10))
# Save results
three_way_df %>% tidy_table(table_cols) %>%
  write.csv("three_way_effects/ethnic_idaci_prior.csv", row.names = F)
```

```{r}
# Ethnicity X FSM X Prior Attainment
# Filter data and sort by CAG diff
three_way_df <- data %>% filter(factor == "Ethnicity X\nFSM X\nPrior Attainment") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
three_way_df <- rbind(head(three_way_df, 10), tail(three_way_df, 10))
# Save results
three_way_df %>% tidy_table(table_cols) %>%
  write.csv("three_way_effects/ethnic_fsm_prior.csv", row.names = F)
```


```{r}
# Ethnicity X IDACI X SEN
# Filter data and sort by CAG diff
three_way_df <- data %>% filter(factor == "Ethnicity X\nIDACI X\nSEN") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
three_way_df <- rbind(head(three_way_df, 10), tail(three_way_df, 10))
# Save results
three_way_df %>% tidy_table(table_cols) %>%
  write.csv("three_way_effects/ethnic_idaci_sen.csv", row.names = F)
```

```{r}
# Gender X IDACI X Prior Attainment
# Filter data and sort by CAG diff
three_way_df <- data %>% filter(factor == "Gender X\nIDACI X\nPrior Attainment") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
three_way_df <- rbind(head(three_way_df, 10), tail(three_way_df, 10))
# Save results
three_way_df %>% tidy_table(table_cols) %>%
  write.csv("three_way_effects/gender_idaci_prior.csv", row.names = F)
```

```{r}
# A FIFTH ONE PERHAPS
# Filter data and sort by CAG diff
three_way_df <- data %>% filter(factor == "Gender X\nIDACI X\nPrior Attainment") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
three_way_df <- rbind(head(three_way_df, 10), tail(three_way_df, 10))
# Save results
three_way_df %>% tidy_table(table_cols) %>%
  write.csv("three_way_effects/gender_idaci_prior.csv", row.names = F)
```


# Four-Way Interactions

```{r}
# Find the 4 way interactions that have greatest differences between max and min
calc_range_interaction(data, n_interactions = 4)
```

```{r}
# Ethnicity X IDACI X Prior Attainment X EAL
# Filter data and sort by CAG diff
four_way_df <- data %>% filter(factor == "Ethnicity X\nIDACI X\nPrior Attainment X\nEAL") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
four_way_df <- rbind(head(four_way_df, 10), tail(four_way_df, 10))
# Save results
four_way_df %>% tidy_table(table_cols) %>%
  write.csv("four_way_effects/4_eal.csv", row.names = F)
```

```{r}
# Ethnicity X IDACI X Prior Attainment X SEN
# Filter data and sort by CAG diff
four_way_df <- data %>% filter(factor == "Ethnicity X\nIDACI X\nPrior Attainment X\nSEN") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
four_way_df <- rbind(head(four_way_df, 10), tail(four_way_df, 10))
# Save results
four_way_df %>% tidy_table(table_cols) %>%
  write.csv("four_way_effects/4_sen.csv", row.names = F)
```

```{r}
# Ethnicity X IDACI X Prior Attainment X SEN
# Filter data and sort by CAG diff
four_way_df <- data %>% filter(factor == "Ethnicity X\nIDACI X\nPrior Attainment X\nGender") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
four_way_df <- rbind(head(four_way_df, 10), tail(four_way_df, 10))
# Save results
four_way_df %>% tidy_table(table_cols) %>%
  write.csv("four_way_effects/4_gender.csv", row.names = F)
```


```{r}
# Ethnicity X IDACI X Prior Attainment X FSM
# Filter data and sort by CAG diff
four_way_df <- data %>% filter(factor == "Ethnicity X\nIDACI X\nPrior Attainment X\nFSM") %>% 
  arrange(cag_diff) %>% filter(welch.p_val <= 0.05)
# Get the top 10 and bottom 10 groups by CAG diff
four_way_df <- rbind(head(four_way_df, 10), tail(four_way_df, 10))
# Save results
four_way_df %>% tidy_table(table_cols) %>%
  write.csv("four_way_effects/4_fsm.csv", row.names = F)
```



